name: Run SlackBot Using RSS

on:
  schedule:
  - cron : '59 14 * * *'
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run_Rss_reader
      run: |
        python "main.py"
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
