name: Run RSS slack

on:
  schedule:
  - cron : '59 14 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run_Rss_reader
      run: |
        python "main.py"
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
